### ISSUE TITLE
Support for TRANSPOSE switch and DRUM P/L/V from 6.3.4

### ISSUE THREAD

**Issue by urbster1** [stijnfrishert/liblsdj#16]

**Comment by stijnfrishert** [comment]
So what _precisely_ changed in 6.3.4? @urbster1

**Comment by urbster1** [comment]
there is now DRUM/FAST/TICK/STEP for P/L/V (except no DRUM for kits), and
TRANPOSE was returned to its former ON/OFF glory

**Comment by stijnfrishert** [comment]
I think we've got this, and pre 6.3.4. covered now. It's a bit of a mess (in Johan's own words), but we should be good.

If not, we'll find out when starting to expose the instrument interface and fix it. Rather certain the latest change doesn't screw over .lsdsng I/O at least.
