### ISSUE TITLE
lsdsng-import -f ignore subfolders (and non-.lsdsng files)

### ISSUE THREAD

**Issue by urbster1** [stijnfrishert/liblsdj#17]
if there are .lsdsng's in a folder and -f is used, if there is a subfolder in the same folder, lsdsng-import will throw an error that the subfolder cannot be opened for reading

**Comment by stijnfrishert** [comment]
Duly noted. It should just pull all .lsdsng's from all sub(-sub-sub-sub)-folders?

**Comment by stijnfrishert** [comment]
And then disregard anything that isn't an .lsdsng

**Comment by urbster1** [comment]
i think so. that way for instance if there is a .sav in there it won't get
added without explicit -s

**Comment by urbster1** [comment]
but also it won't cause an error

**Comment by stijnfrishert** [comment]
Fixed (will be there for next build)!

Also ignores hidden files now (starting with a dot on unix).
