### ISSUE TITLE
lsdsng-tools change KIT P/L/V from FAST to STEP

### ISSUE THREAD

**Issue by urbster1** [stijnfrishert/liblsdj#24]
Using lsdsng-export and lsdsng-import on this .sav changes KIT instrument 26 from FAST to STEP.
https://defensemech.com/REVISION.sav

**Comment by urbster1** [comment]
tested and it seems lsdsng-export is the culprit. also showing weird garbled instrument names for some instruments

**Comment by urbster1** [comment]
Here's what I think (and feel free to delete this bug and create an enhancement) - lsdsng-export and -import should be entirely version-agnostic. They should only deal with compression/decompression and reading bytes for song titles/version numbers. A new tool should be created to convert songs between versions.

**Comment by urbster1** [comment]
also, it's naming all of the instruments after the last instrument or something. I dunno, something really strange is going on lol

**Comment by stijnfrishert** [comment]
Gonna keep this issue, because the bug is still a bug even if we split this off in different tools. I'll create another issue for that.

**Comment by urbster1** [comment]
The names don't seem to be garbled in v1.0. It also seems like the volume
col in tables is getting weird data. I can provide another example lsdsng
if that will help

**Comment by stijnfrishert** [comment]
Fixed PLV, but turns out loop2 was also written incorrectly. Both are fixed
