### ISSUE TITLE
lsdsng-import/export shouldn't change versions

### ISSUE THREAD

**Issue by stijnfrishert** [stijnfrishert/liblsdj#26]
We could possibly create a different tool to change version numbers for lsdsng's.

@urbster1 Problem though, what is the format version of the .sav output on import? The individual lsdsng's could have different versions.

**Comment by stijnfrishert** [comment]
Oh wait that's the project version that's stored in lsdsng. Right!

**Comment by stijnfrishert** [comment]
From what I can see lsdsng-export writes the lsdsng's keeping the individual song format versions intact.

**Comment by stijnfrishert** [comment]
...and so does lsdsng-import. So I guess I made this in vain, or perhaps already fixed it in the past!

**Comment by urbster1** [comment]
Yeah I'm not sure what I was thinking, I might have opened this? either
way, it doesn't mess with version

**Comment by stijnfrishert** [comment]
Thanks for confirming :)
