### ISSUE TITLE
Instrument names are garbled

### ISSUE THREAD

**Issue by stijnfrishert** [stijnfrishert/liblsdj#27]
Apparently instrument names are garbled in v1.1. I've tried lsdsng-export myself, but it seems to be working fine (import uses the same read/write code).

@urbster1 Could you provide a pre-tooling .sav that demonstrates this behaviour?

**Comment by urbster1** [comment]
try this one (rename from .txt to .sav)
[Dnb(2).sav.txt](https://github.com/stijnfrishert/liblsdj/files/2257604/Dnb.2.sav.txt)

**Comment by urbster1** [comment]
should lsdsng-export output be bit-exact with LSDManager?

**Comment by stijnfrishert** [comment]
No it shouldn't; LSDManager actually doesn't follow the official rules of the compression algo described on the wiki and lsdsng-export does, so there's bound to be a few bits off. But (apart from any bugs) those off bits are in the compression data, not the...compressee data.

**Comment by stijnfrishert** [comment]
Fixed!

**Comment by urbster1** [comment]
ahaha oops

**Comment by urbster1** [comment]
thanks!
