### ISSUE TITLE
Incorporate changes of 6.7.0 and 6.8.0 (WAV speed and length)

### ISSUE THREAD

**Issue by stijnfrishert** [stijnfrishert/liblsdj#31]
http://littlesounddj.wikia.com/index.php?title=.sav_structure&diff=5227&oldid=5214

**Comment by urbster1** [comment]
unfortunately this was a format-breaking change and wave instruments no longer import/export properly on 6.8.0

**Comment by urbster1** [comment]
may as well make this 6.8.1 since now grooves are also changed!

**Comment by stijnfrishert** [comment]
Could you make that into a new issue? I like to keep these things seperated.

**Comment by urbster1** [comment]
no

**Comment by stijnfrishert** [comment]
Perfect

**Comment by stijnfrishert** [comment]
Ok, so apparently this changed in 6.7.0 and not 6.8.0, but Johan has eradicated 6.7.0 from existence. Still, and I put this here for future reference: the wav speed changed with format version 6.

6.8.0 moves to fmt version 7, presumably for the groove changes, but WAV speed already changed at v7.

**Comment by stijnfrishert** [comment]
WAV Speed and length changed in 6.7.0 (v6) and then again in 6.8.0 (v7) because the defaults were wrong.
