### ISSUE TITLE
lsdj-deep-clean tool

### ISSUE THREAD

**Issue by urbster1** [stijnfrishert/liblsdj#40]
It would be really nice to have a tool that would reduce duplicate tables/instruments to single instances, and reduce phrases that are equivalent when transpose is applied, and apply appropriate TSP value in chain transpose column (comparison between phrases should ignore pulse/wave instruments with transpose=off).

Presumably, if table clean is applied before instrument clean which is applied before phrase clean, this order of operations probably has the best chance of reducing the most memory at once.

**Comment by urbster1** [comment]
Flags could be --instruments/-i, --phrases/-p, --tables/-t, --transpose/???
Default=remove all dups?
After cleaning, report output of how many dups were removed and which ones

Could take entire .sav or single .lsdsng

**Comment by stijnfrishert** [comment]
Exactly what I had in mind, yes. This would come be such a nice "post-processing" step before album release or something.

**Comment by urbster1** [comment]
Yeah I was just thinking yesterday how nice it would be to de-duplicate
chains

**Comment by urbster1** [comment]
not sure if this deserves its own issue so I'm throwing it in here: a way to display information about song(s). specifically I'm interested in what's unused, for instance if a phrase contains data but is not used in the song, it would be interesting to find out before it's cleaned. toasterpastries also suggested it would be useful to find out which sample kits are being used, presumably throughout the entire save.

**Comment by stijnfrishert** [comment]
Yes, both good suggestions!

So what do you think: separate tool called `lsdj-inspect` or something to output information about any .sav or .lsdsng? Print functionality from export could perhaps also be moved in there.

Then export and import would be literally just for export and import. Clean for cleaning, mono for mono...izing.

**Comment by urbster1** [comment]
ok so per our discussion in facebook earlier:

1. synth dedup is not possible nor wanted
2. phrase dedup + adding tsp might be tricky and not worth it
3. LSDJ does not dedup tables, chains, or instruments so these should be the focus for v1.0
4. maybe it's best to just request #3 as a feature native to LSDJ

**Comment by urbster1** [comment]
update: this issue can be closed. latest versions of LSDJ now de-dupe tables, chains, and instruments
