### ISSUE TITLE
lsdj-wavetable-import save support

### ISSUE THREAD

**Issue by urbster1** [stijnfrishert/liblsdj#41]
I just thought it would be nice if we don't bother to worry about which song we're patching into, just patch directly into whatever is in the save file working memory

**Comment by stijnfrishert** [comment]
Yeah, perhaps leaving out the song index means working memory song

**Comment by urbster1** [comment]
I came here to add this as an issue and it's already been added! hahaha XD

**Comment by urbster1** [comment]
Just to clarify, I definitely think we should only worry about the working memory song and not worry about requiring an index. Open to feedback on that

**Comment by stijnfrishert** [comment]
Well, it's already in there so why not make that opt-in for the occasional use?

**Comment by stijnfrishert** [comment]
Ok, wait. But right now this tool only imports into .lsdsng's, right? So what you're suggesting is another mode in which it takes in a .sav and patches into the wm song?

**Comment by stijnfrishert** [comment]
Ok, makes sense. Will do.
