### ISSUE TITLE
lsdj-wavetable-import: trying to write noise.snt doesn't create all values properly

### ISSUE THREAD

**Issue by urbster1** [stijnfrishert/liblsdj#42]
trying to write this .snt into this save file doesn't create the values as saved in the .snt

[snttest.zip](https://github.com/stijnfrishert/liblsdj/files/2554182/snttest.zip)

**Comment by stijnfrishert** [comment]
Thanks, will look at this when I find the time :)

**Comment by stijnfrishert** [comment]
Ehm, it does on my end?

You double checked with a hex editor if they correspond? If not, are some frames incorrect, or all of them?

I used `lsdj-wavetable-import "./(EMPTY).00.WM.lsdsng" "./noise.snt" 0`

**Comment by urbster1** [comment]
let me check this again...

**Comment by urbster1** [comment]
I used `lsdj-wavetable-import.exe` (EMPTY).00.lsdsng noise.snt 7` and got this save. notice how frames 75-7F are the same but should be different...
[(EMPTY).00.lsdsng.zip](https://github.com/stijnfrishert/liblsdj/files/2621530/EMPTY.00.lsdsng.zip)

**Comment by stijnfrishert** [comment]
Ok thanks, I'll check with these settings! .lsdsng is compressed yes, so you wouldn't be able to copy/paste in the wavetable manually. (I was just talking about comparing hex in the .snt with the visual byte values surrounding the waves in lsdj).

**Comment by urbster1** [comment]
gotcha, thanks!

**Comment by stijnfrishert** [comment]
Ok, weird stuff is happening, because on my system it totally runs fine (I did use --force). How many frames does the cmd line say it wrote after execution?

**Comment by urbster1** [comment]
what if you don't use force but just use 'y' at the prompt? let me run
again and see

**Comment by urbster1** [comment]
`Some of the wavetable frames you are trying to overwrite already contain data. Do you want to continue? y/n
> y
Successfully wrote 16 frames starting at 96 to (EMPTY).00.lsdsng`

**Comment by stijnfrishert** [comment]
I'll try without force. Also, did you use another index than 7 this time, because otherwise that 96 doesn't make sense.

**Comment by urbster1** [comment]
Screenshots of the hex values
![image](https://user-images.githubusercontent.com/5685593/49473362-d817b480-f7df-11e8-9da8-4ae60fb2c4b6.png)
![image](https://user-images.githubusercontent.com/5685593/49473379-e4037680-f7df-11e8-956d-b7a76fee4c5f.png)

**Comment by urbster1** [comment]
yeah sorry i used 6. but it's doing the same thing

**Comment by urbster1** [comment]
could it be an issue with lsdsng-import then? i have no way to check if it's valid in the lsdsng itself

**Comment by stijnfrishert** [comment]
Can you send just the exported .lsdsng?

**Comment by urbster1** [comment]
[(EMPTY).00.zip](https://github.com/stijnfrishert/liblsdj/files/2646163/EMPTY.00.zip)

**Comment by urbster1** [comment]
ok! very weird. thanks!

**Comment by stijnfrishert** [comment]
Problem was that the file wasn't opened as binary
