### ISSUE TITLE
Wildcard support for lsdsng-tools

### ISSUE THREAD

**Issue by urbster1** [stijnfrishert/liblsdj#44]
Does Boost support e.g. `lsdsng-export -p *.sav`?

**Comment by stijnfrishert** [comment]
Nope, don't think so. But we could have this work with folders, and then print all sav's inside?

**Comment by urbster1** [comment]
That would be good too!

**Comment by stijnfrishert** [comment]
Printing a folder will print all .sav files within it :)

**Comment by urbster1** [comment]
Thanks!!
