### ISSUE TITLE
When importing folder, name save after folder name by default

### ISSUE THREAD

**Issue by urbster1** [stijnfrishert/liblsdj#45]
If lsdsng-import is used to compile a folder of lsdsng's into a save file, it would be great if the name of the save file was the folder name by default and not the name of the first lsdsng in that folder :)

**Comment by stijnfrishert** [comment]
Totally agree!

**Comment by stijnfrishert** [comment]
Several issues are lining up for a next update, I'll see when I can find the time :)

**Comment by urbster1** [comment]
Can you tell I'm trying to organize my stuff for an upcoming set? ;)

**Comment by urbster1** [comment]
honestly instead of making these issues I should just learn to submit pull requests and make your life easier
