### ISSUE TITLE
Change lsdj-wavetable-import parameters, because they're confusing

### ISSUE THREAD

**Issue by urbster1** [stijnfrishert/liblsdj#50]
Update help text to include

1. .sav save file working memory import (does -o functionality need to change?)

also

 2. I was thinking of otherwise revamping the arguments. I remember having a discussion earlier about providing arguments but after using it I realized I would really much rather provide a couple flags instead of using argument index. it seems simpler if usage looks more like this `wavetable-import -w wavetables.snt -s 0 save.sav` because I utterly cannot remember the order of all 3 arguments and I kind of don't want to have to care about it ahaha... uhh I'm lazy.

then the help text could be something like

```
Usage:
lsdj-wavetable-import [destination.lsdsng|.sav] [wavetables.snt] [synth 0-F|index 00-FF]

Options:
  -h [ --help ]         Help screen
  -0 [ --zero ]         Pad the synth with empty wavetables if the .snt file < 256 bytes
  -f [ --force ]        Force writing the wavetables, even though non-default data may be in them
  -o [ --output ] arg   The output .lsdsng (or .sav?) to write to
  -i [ --index ]        The wavetable index 00-FF where the wavetable data should be written
  -s [ --synth ] arg    The synth number 0-F where the wavetable data should be written
  -v [ --verbose ]      Verbose output
  -w [ --wavetable ] arg    The .snt wavetable data to write
```
I opted to specify either index or synth, and also refer to all wave frames as wavetables because it is a wavetable synth (also the utility is named "lsdj-wavetable-import"). Maybe if the argument index behavior is left intact, there's no need for -i if we can tell the difference between 0-F (synth) and 00-FF (index) because we can detect which one they mean.

None of this is urgent but I figured I'd document it :smiley:

**Comment by stijnfrishert** [comment]
Agreeing on the "can't remember the order" part. Let's change that for 1.2.3.

**Comment by stijnfrishert** [comment]
@urbster1 Started working on this.

**Comment by urbster1** [comment]
Thanks!

**Comment by stijnfrishert** [comment]
I think this is done, but could you do some testing, @urbster1? I'll be able to send a build tonight probably.

**Comment by urbster1** [comment]
Sure!

**Comment by urbster1** [comment]
ok so given that using flags doesn't make sense if the parameters aren't optional, can we detect what's what based on file extension so that we can put a .snt file in a .sav/.lsdsng regardless of order?
