### ISSUE TITLE
lsdsng-import save file merging

### ISSUE THREAD

**Issue by urbster1** [stijnfrishert/libLSDJ#51]
Since we're already accepting .sav as input to glom .lsdsng's onto, why not accept multiple sav's to merge together?

**Comment by stijnfrishert** [comment]
Makes sense!

**Comment by stijnfrishert** [comment]
* I removed the `--sav` flag, which was used to append songs to.
* Now you can just include multiple `.sav`'s as inputs
* If you `-o` flag mentions a sav that is also in the inputs, it's overwritten
