### ISSUE TITLE
Look into using a boost alternative

### ISSUE THREAD

**Issue by stijnfrishert** [stijnfrishert/liblsdj#59]
- Distribute boost along
 - std::filesystem
 - https://github.com/cginternals/cppfs
 - more?

**Comment by urbster1** [comment]
std::fs is c++17+ so i would great appreciate this :)

**Comment by stijnfrishert** [comment]
https://github.com/gulrak/filesystem

**Comment by stijnfrishert** [comment]
Went got ghc::filesystem and popl
