### ISSUE TITLE
lsdsng-export giving error 'rb not found at 0x7FF0'

### ISSUE THREAD

**Issue by urbster1** [stijnfrishert/liblsdj#60]
however you will find rb at 0x7FF0. save attached
[Ganondorofu - Black Hopes Of Yellow Dreams - BHOYD lsdj v6_8_4 (1).zip](https://github.com/stijnfrishert/liblsdj/files/3780166/Ganondorofu.-.Black.Hopes.Of.Yellow.Dreams.-.BHOYD.lsdj.v6_8_4.1.zip)

**Comment by urbster1** [comment]
per discussion that was only the song in working memory. but the 'rb' byte situation will be revisisted

**Comment by stijnfrishert** [comment]
Discussed with Johan; he's updating LSDJ to write the three 'rb' locations on every new song, and I'll loosen the check to pass if any of the three locations has been written (which is what LSDj does too)
