### ISSUE TITLE
lsdsng-import shouldn't ignore FX/SPEED

### ISSUE THREAD

**Issue by urbster1** [stijnfrishert/liblsdj#61]
i thought instrument data was supposed to carry the whole chunk when importing? maybe something is weird but FX/SPEED was reset to 0 for inst 0E in this song. lsdsng (from LSDManager) and sav from lsdsng-import included. tested in v7.1.4
[4thsriff.zip](https://github.com/stijnfrishert/liblsdj/files/3933947/4thsriff.zip)

**Comment by urbster1** [comment]
FX/SPEED should show 1 for inst 0E (not zero)

**Comment by stijnfrishert** [comment]
Thanks, I'll take a look when I find the time!

**Comment by stijnfrishert** [comment]
Dependent upon #67

**Comment by urbster1** [comment]
FX/SPEED has been renamed to CMD/RATE

**Comment by stijnfrishert** [comment]
Thanks! It's probably the same byte, but changes like these do propose an interesting question. What do we call these functions?

`lsdj_instrument_set_fx_speed()`? `lsdj_instrument_set_cmd_rate()`? Should we include both while one calls the other? People might look for one function over the other, depending on the LSDj version the library user is used to.

**Comment by urbster1** [comment]
This one seems obvious, just call it cmd_rate since that's what it will be
in the first stable version since the feature was added. But the P/L/V =>
PITCH change brings up a similar issue since past stable versions have had
P/L/V and future versions will have PITCH (likewise PITCH vs FINETUNE in
kits etc)

**Comment by stijnfrishert** [comment]
All right, that's good news for this issue, and then we'd have to think about P/L/V

**Comment by urbster1** [comment]
right. and previously it was also called VIB TYPE. so we might have to
think it through a bit

**Comment by stijnfrishert** [comment]
So what setting is this exactly? Cause I didn't come across it in any of the version changes.

**Comment by urbster1** [comment]
i got confused and started talking about something else. CMD/RATE (first known as FX/SPEED) controls the speed of C commands as well as P in noise channel (and P/L/V when pitch is set to TICK).

**Comment by stijnfrishert** [comment]
Hmmm, ok I'm not entirely sure where in Johan's upgrade code that's featured, so I'll look into that too.

**Comment by stijnfrishert** [comment]
Ok, this issue can actually be closed, the new v2 shouldn't ignore any settings at all anymore.

Opened #78 for post-v2 handling
