### ISSUE TITLE
lsdsng-export -f argument not working

### ISSUE THREAD

**Issue by urbster1** [stijnfrishert/liblsdj#62]
i got a weird error that it couldn't create a folder
```
lsdsng-export -f save.sav
ERROR: could not open [C:\folder\song.lsdsng] for writing
```

**Comment by urbster1** [comment]
i was running the command line as administrator so there was no reason for it to fail...

**Comment by stijnfrishert** [comment]
Thanks, I'll take a look when I find the time!
