### ISSUE TITLE
Support for custom allocators

### ISSUE THREAD

**Issue by tommitytom** [stijnfrishert/liblsdj#69]
There are various places where `malloc` and `free` are used - it would be nice to be able to specify functions to be used in their place

**Comment by stijnfrishert** [comment]
* Implemented for Saves and Projects. 
 * There are some other structures that malloc, such as Chain, Table, etc.
 * Not sure what to do with errors

**Comment by stijnfrishert** [comment]
Alright, this works now. Still gotta think about errors, but that's a separate issue.

Closing this for now, you can expect this in the upcoming 2.0.0 release, @tommitytom! :)
