### ISSUE TITLE
Add querying functions for the new envelope system

### ISSUE THREAD

**Issue by stijnfrishert** [stijnfrishert/libLSDJ#75]

**Comment by stijnfrishert** [comment]
Moving this to post v2.0.0. Due to the new rewrite it's like we don't actually support the new envelope system (no byte gets left behind, SIR!). It's just that lib users won't be able to query for information about the new envelope parameters, and:

1. I'd need to give some thought to what the API should look like
2. It's not as if any of the tools are currently using them
3. The envelope feature isn't actually officially declared stable
4. I'd like to get v2 out.

**Comment by urbster1** [comment]
just FYI there is an 8.5.1 stable candidate out. however there are going to be updates to the envelopes (moving from x0-x7 to x0-xF) due to software volume implementation so it probably makes sense to wait to implement until at least v8.8.x is released

**Comment by stijnfrishert** [comment]
Continued at #91
