### ISSUE TITLE
Make v2 handle Drum MAX again

### ISSUE THREAD

**Issue by stijnfrishert** [stijnfrishert/liblsdj#80]
@urbster1 You said something about this being removed again in some version?

**Comment by urbster1** [comment]
It was removed in v6.3.3, although that byte is not overwritten, so if you
load a v6.1 song into v6.3+ and then back to 6.1, it will still apply DRM
MAX as it was originally set.

**Comment by stijnfrishert** [comment]
Ok that's good news. The set/get funcs could still exist, and beyond 6.3+ it just won't do anything for LSDj :)
