### ISSUE TITLE
lsdsng-import directory recursion

### ISSUE THREAD

**Issue by urbster1** [stijnfrishert/libLSDJ#83]
If `-f` is used by lsdsng-export to put songs in folders, it would be nice to recursively check subfolders for .lsdsng files.

**Comment by stijnfrishert** [comment]
@urbster1 Wait, the title mentions `lsdsng-import`, but the description mentions `lsdsng-export`. Which one are we talking about?

**Comment by urbster1** [comment]
both - lsdsng-export places lsdsng files into their own folders with the -f
option. so when calling lsdsng-import, it would be nice to have folder
input as well. otherwise you're stuck manually adding each lsdsng because
each one is in a separate folder. make sense?

**Comment by urbster1** [comment]
actually I think it does have folder input right? but it won't check
subfolders, so if you have one folder as the input but the folder contains
a set of subfolders each with a .lsdsng, none of those songs are added to
the import. that's what the issue is about IIRC

**Comment by stijnfrishert** [comment]
Aah right! Yeah, it does have folder support, but doesn't read them recursively. 

Except for the fact that I happened to add that yesterday when refactoring some code, so I guess this is solved then 😀
