### ISSUE TITLE
lsdsng-import songs imported as EMPTY

### ISSUE THREAD

**Issue by urbster1** [stijnfrishert/libLSDJ#84]
a number of the following songs, when imported together into one save, show EMPTY. example lsdsng's attached (attachment removed)

**Comment by urbster1** [comment]
thinking about this now, this is probably the same bug as https://github.com/stijnfrishert/libLSDJ/issues/82

**Comment by stijnfrishert** [comment]
Yeah, quite certain this is the same bug. I'll send you a new version to see if that fixed it.
