### ISSUE TITLE
Multiple ideas!

### ISSUE THREAD

**Issue by INFU-AV** [stijnfrishert/libLSDJ#86]
Hi 4ntler, thanks for developing this tool, I absolutely love it! I have couple ideas that IMO would improve general experience of usage, making it more accessible and useful:

-Little gui to select the exact project from save
-Ability to import/extract single songs to/from the save
-Ability to reorder/rename songs inside save itself
-Merging 2/multiple songs together (or parts of it, like only phrases, or only instruments) for a liveset situation
-Stats showing usage of space/memory for selected save (how many phrases we have free, how many free instruments etc.)

**Comment by urbster1** [comment]
Hello,
Re: ability to extract single song to/from sav, this is already possible, see flags `-i` and `-n`:
```
lsdsng-export mymusic.sav|folder

Version: 2.0.0

Options:
  -h, --help            Show the help screen
  -v, --verbose         Verbose output during export
  --noversion           Don't add version numbers to the filename
  -f, --folder          Put every lsdsng in its own folder
  -p, --print           Print a list of all songs in the sav, instead of exporting
  -d, --decimal         Use decimal notation for the version number, instead of hex
  -u, --underscore      Use an underscore for the special lightning bolt character, instead of x
  -o, --output arg      Output folder for the lsdsng's
  -i, --index arg       Single out a given project index to export, 0 or more
  -n, --name arg        Single out a given project by name to export
  -w, --working-memory  Single out the working-memory song to export
```
Importing a single lsdsng file (or more than one) to an existing sav with `lsdsng-import` is also supported, see flag `-s`:
```
lsdsng-import -o output.sav song1.lsgsng song2.lsdsng...

Version: 2.0.0

Options:
  -h, --help        Show the help screen
  -v, --verbose     Verbose output during import
  -o, --output arg  The output file (.sav)
  -s, --sav arg     A sav file to append all .lsdsng's to
```

**Comment by INFU-AV** [comment]
That's so nice, thanks urbster!

Still, GUI version would be definitely a big plus! :)

**Comment by urbster1** [comment]
Keep in mind this is a software library and the tools are mostly proof of
concept - anyone can use this library in their software. For one example of
a project using libLSDJ that has a GUI, check out
https://github.com/InspectorConstructor/lsdjSongManager (although it needs
to be updated to libLSDJ v2)

**Comment by stijnfrishert** [comment]
Hey @INFU-AV! Thanks for taking the time to post your ideas, much appreciated :)

 - A graphical user interface is probably one of the most popular but also hardest feature requests. It's not something that's initially in the mission statement of LibLSDJ (as @urbster1 mentions, the library itself is free for people to build their own GUI with), though in the future I may be someday be crazy enough to do so.
 - As said, importing and exporting songs is something already supported
 - Reordering and renaming songs is a solid idea. Not sure what the interface would be in terms of usage, but we can think that through
 - Yeah, would be really cool. I think this would warrant a graphic user interface as well, though.
    - As a side note, I have been considering creating an `.lsdinst` format that you can use to import/export instruments
 - This is also a solid idea, yes. Make an `lsdj-stats` tool? 🤔

**Comment by stijnfrishert** [comment]
@INFU-AV I've created several other issues where we can discuss the separate ideas further. Closing this, if you'd like to talk further I'd welcome any input in the new issues.

#96 #97 #98
